spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation
    username: postgres
    password: lechuga
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true